#!/usr/bin/env python

import socket
import time

def main(ip, port, delay):
    sock = socket.socket(socket.AF_INET,
                         socket.SOCK_DGRAM)

    message = '$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47'

    while True :
        try:
            message = message + u"\r\n"
            sock.sendto(message.encode("utf-8"), (ip, port))
            time.sleep(delay)
        except KeyboardInterrupt:
            sock.close()
        except Exception as msg:
            print(msg)
            sock.close()

if __name__ == '__main__':
    main('127.0.0.1', 10110, 2)
